require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/AlignLeftLetBrace:
  Enabled: true
