require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/yard/**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/support/**/*.rb'
    - '*.gemspec'

Layout/LineLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/PredicateMatcher:
  Exclude:
    - 'spec/integration/yard/**/*_spec.rb'

RSpec/DescribedClass:
  Exclude:
    - 'spec/integration/yard/**/*_spec.rb'
    - 'spec/integration/readme/**/*_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/integration/yard/**/*_spec.rb'
    - 'spec/integration/readme/**/*_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/integration/yard/**/*_spec.rb'
    - 'spec/integration/readme/**/*_spec.rb'
    - spec/lib/sinclair_spec.rb
    - spec/support/shared_examples/sinclair.rb

RSpec/NestedGroups:
  Max: 5
  Exclude:
    - spec/integration/yard/**/*.rb

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Enabled: false
