require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/support/**/*.rb'

Metrics/LineLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/InstanceVariable:
  Exclude:
    - spec/integration/yard/sinclair/method_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/instance_block_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/instance_method_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/class_block_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/class_method_definition_spec.rb
    - spec/lib/sinclair/method_definition/instance_block_definition_spec.rb
    - spec/lib/sinclair/method_definition/instance_method_definition_spec.rb
    - spec/lib/sinclair/method_definition/class_block_definition_spec.rb
    - spec/lib/sinclair/method_definition/class_method_definition_spec.rb
    - spec/lib/sinclair/method_definition_spec.rb
    - spec/lib/sinclair/method_definition/block_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/block_definition_spec.rb


RSpec/MultipleExpectations:
  Exclude:
    - spec/integration/yard/sinclair/method_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/instance_block_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/instance_string_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/instance_method_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/class_block_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/class_string_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/class_method_definition_spec.rb
    - spec/lib/sinclair_spec.rb
    - spec/integration/readme/my_model_spec.rb
    - spec/integration/yard/sinclair/method_definition/block_definition_spec.rb
    - spec/integration/yard/sinclair/method_definition/string_definition_spec.rb

RSpec/NestedGroups:
  Max: 4
  Exclude:
    - spec/integration/yard/**/*.rb
