require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

RSpec/AlignLeftLetBrace:
  Enabled: true

RSpec/InstanceVariable:
  Exclude:
    - 'spec/integration/yard/sinclair/method_definition_spec.rb'
    - 'spec/lib/sinclair/method_definition_spec.rb'

RSpec/MultipleExpectations:
  Exclude:
    - spec/integration/yard/sinclair/method_definition_spec.rb
    - spec/lib/sinclair_spec.rb

RSpec/NestedGroups:
  Max: 4
  Exclude:
    - spec/integration/yard/**/*.rb
