version: '2'
services:
  base: &base
    image: ruby:2.4.0
    working_dir: /home/app/sinclair
    volumes:
      - .:/home/app/sinclair
      - sinclair_gems_2_4_0:/usr/local/bundle

  #################### CONTAINERS ####################

  sinclair:
    <<: *base
    container_name: sinclair
    command: /bin/bash -c 'bundle install && bundle exec rspec'

volumes:
  sinclair_gems_2_4_0:
