version: '3'
services:
  base: &base
    image: sinclair
    working_dir: /home/app/app
    volumes:
      - .:/home/app/app

  base_build:
    <<: *base
    build: .
    command: echo done

  sinclair:
    <<: *base
    container_name: sinclair
    depends_on: [base_build]
    command: /bin/bash -c 'rspec'

  test_all:
    <<: *base
    depends_on: [base_build]
    command: /bin/bash -c 'rspec && yard && rake yardstick_measure && rake verify_measurements'

  sinclair_circleci:
    <<: *base
    image: sinclair_circleci
    container_name: sinclair_circleci
    volumes:
      - .:/home/circleci/project
    working_dir: /home/circleci/project
    command: /bin/bash
    build:
      dockerfile: Dockerfile.circleci
