ignore:
  - lib/sinclair/model/builder.rb
  - lib/sinclair/comparable/class_methods.rb
  - lib/sinclair/exception.rb
  - lib/sinclair/matchers/add_method.rb
  - lib/sinclair/matchers/add_method_to.rb
  - lib/sinclair/matchers/base.rb
  - lib/sinclair/matchers/change_method_on.rb
  - lib/sinclair/matchers/method_to.rb
  - lib/sinclair/version.rb
