ignore:
  - lib/sinclair/matchers/add_method_to.rb
  - lib/sinclair/matchers/add_method.rb
  - lib/sinclair/version.rb
  - lib/sinclair/method_builder/base.rb
  - lib/sinclair/exception.rb
  - lib/sinclair/matchers/method_to.rb
  - sinclair/matchers/base.rb
  - lib/sinclair/matchers/change_method_on.rb
