threshold: 99.2
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - Sinclair::Configurable#config
      - Sinclair::Configurable#reset_config
      - Sinclair::Configurable#configure
      - Sinclair::EqualsChecker#initialize
      - Sinclair::Options#==
      - Sinclair::OptionsParser#options
      - Sinclair::OptionsParser#options_object
      - Sinclair::Matchers#add_method
      - Sinclair::Matchers#add_class_method
      - Sinclair::Matchers#change_method
      - Sinclair::Matchers#change_class_method
  ReturnTag:
    enabled: true
    exclude:
      - Sinclair::Matchers::AddClassMethodTo#raise_block_syntax_error
      - Sinclair::Matchers::AddInstanceMethodTo#raise_block_syntax_error
      - Sinclair::MethodBuilder#build_from_definition
      - Sinclair::Matchers::ChangeClassMethodOn#raise_block_syntax_error
      - Sinclair::Matchers::ChangeInstanceMethodOn#raise_block_syntax_error
  Summary::Presence:
    enabled: true
    exclude:
      - Sinclair::Config::MethodsBuilder#initialize
      - Sinclair::ConfigFactory#initialize
      - Sinclair::EnvSettable::Builder#initialize
      - Sinclair::Exception::InvalidOptions#initialize
      - Sinclair::EqualsChecker#initialize
      - Sinclair::InputHash#initialize
      - Sinclair::Matchers::AddInstanceMethodTo#initialize
      - Sinclair::Matchers::AddClassMethodTo#initialize
      - Sinclair::Matchers::AddInstanceMethodTo#instance
      - Sinclair::Matchers::AddMethod#initialize
      - Sinclair::Matchers::AddMethodTo#initialize
      - Sinclair::Matchers::Base#initialize
      - Sinclair::Matchers::ChangeClassMethodOn#initialize
      - Sinclair::Matchers::ChangeInstanceMethodOn#initialize
      - Sinclair::MethodBuilder
      - Sinclair::MethodBuilder::Base#initialize
      - Sinclair::MethodBuilder::Accessor#initialize
      - Sinclair::MethodDefinition#initialize
      - Sinclair::MethodDefinition::CallDefinition#initialize
      - Sinclair::MethodDefinition::BlockDefinition#initialize
      - Sinclair::MethodDefinition::StringDefinition#initialize
      - Sinclair::Options#initialize
      - Sinclair::Options::Builder#initialize
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
