threshold: 100
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - Sinclair::OptionsParser#options
      - Sinclair::OptionsParser#options_object
  ReturnTag:
    enabled: true
    exclude:
      - Sinclair#klass
      - Sinclair::Matchers::AddMethod#method
      - Sinclair::Matchers::AddMethodTo#method
      - Sinclair::Matchers::AddMethodTo#instance
      - Sinclair::MethodDefinition#name
      - Sinclair::MethodDefinition#code
      - Sinclair::MethodDefinition#block
      - Sinclair::OptionsParser#options
      - Sinclair::OptionsParser#options_object
      - Sinclair::Matchers::AddMethodTo#raise_block_syntax_error
  Summary::Presence:
    enabled: true
    exclude:
      - Sinclair#klass
      - Sinclair::Matchers::AddMethod#method
      - Sinclair::Matchers::AddMethodTo#method
      - Sinclair::Matchers::AddMethodTo#instance
      - Sinclair::MethodDefinition#name
      - Sinclair::MethodDefinition#code
      - Sinclair::MethodDefinition#block
      - Sinclair::OptionsParser#options
      - Sinclair::OptionsParser#options_object
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
