threshold: 100
require_exact_threshold: false
rules:
  ApiTag::Presence:
    enabled: true
    exclude: []
  ApiTag::Inclusion:
    enabled: true
    exclude: []
  ApiTag::ProtectedMethod:
    enabled: true
    exclude: []
  ApiTag::PrivateMethod:
    enabled: true
    exclude: []
  ExampleTag:
    enabled: true
    exclude:
      - Sinclair::Configurable#config
      - Sinclair::Configurable#reset_config
      - Sinclair::Configurable#configure
      - Sinclair::OptionsParser#options
      - Sinclair::OptionsParser#options_object
  ReturnTag:
    enabled: true
    exclude:
      - Sinclair::Matchers::AddClassMethodTo#raise_block_syntax_error
      - Sinclair::Matchers::AddInstanceMethodTo#raise_block_syntax_error
      - Sinclair::MethodBuilder#build_from_definition
  Summary::Presence:
    enabled: true
    exclude:
      - Sinclair::Config::MethodsBuilder#initialize
      - Sinclair::ConfigFactory#initialize
      - Sinclair::EnvSettable::Builder#initialize
      - Sinclair::Exception::InvalidOptions#initialize
      - Sinclair::InputHash#initialize
      - Sinclair::Matchers::AddClassMethodTo#initialize
      - Sinclair::Matchers::AddInstanceMethodTo#instance
      - Sinclair::Matchers::AddMethod#initialize
      - Sinclair::Matchers::AddMethodTo#initialize
      - Sinclair::MethodBuilder
      - Sinclair::MethodBuilder::Base#initialize
      - Sinclair::MethodDefinition#initialize
      - Sinclair::MethodDefinition::BlockDefinition#initialize
      - Sinclair::MethodDefinition::StringDefinition#initialize
  Summary::Length:
    enabled: true
    exclude: []
  Summary::Delimiter:
    enabled: true
    exclude: []
  Summary::SingleLine:
    enabled: true
    exclude: []
